#!/usr/bin/env bash
#
# AWX Setup Script
#
# This script:
# 1. Creates necessary directories and files
# 2. Generates secure passwords if not set
# 3. Starts AWX services
# 4. Configures initial project, inventory, and job templates
#
# Usage:
#   ./setup_awx.sh           # Full setup
#   ./setup_awx.sh --start   # Just start services
#   ./setup_awx.sh --config  # Just configure AWX (after services are running)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Generate secure password
generate_password() {
    openssl rand -base64 24 | tr -d '/+=' | head -c 24
}

# Create .env file if it doesn't exist
setup_env() {
    if [[ ! -f .env ]]; then
        log_info "Creating .env file with secure defaults..."
        cat > .env << EOF
# Generated by setup_awx.sh on $(date)
AWX_DB_PASSWORD=$(generate_password)
AWX_ADMIN_USER=admin
AWX_ADMIN_PASSWORD=$(generate_password)
AWX_ADMIN_EMAIL=admin@localhost
AWX_SECRET_KEY=$(openssl rand -base64 32)
AWX_WEB_PORT=8052
PUSHGATEWAY_PORT=9091
EOF
        chmod 600 .env
        log_info "Generated .env file. SAVE THESE CREDENTIALS:"
        echo "========================================"
        grep -E "^AWX_ADMIN" .env
        echo "========================================"
    else
        log_info ".env file already exists, using existing configuration"
    fi
    source .env
}

# Setup SSH credentials directory
setup_ssh() {
    log_info "Setting up SSH credentials directory..."
    mkdir -p credentials/ssh
    chmod 700 credentials/ssh

    if [[ ! -f credentials/ssh/id_rsa ]]; then
        log_warn "No SSH key found in credentials/ssh/"
        log_warn "Copy your SSH private key to credentials/ssh/id_rsa"
        log_warn "Or generate one with: ssh-keygen -t rsa -b 4096 -f credentials/ssh/id_rsa -N ''"
    fi
}

# Setup project directory
setup_projects() {
    log_info "Setting up projects directory..."
    mkdir -p projects

    # Link the ansible directory if not already linked
    if [[ ! -L projects/slurm-maintenance ]] && [[ ! -d projects/slurm-maintenance ]]; then
        ln -sf ../ansible projects/slurm-maintenance
        log_info "Linked ansible directory to projects/slurm-maintenance"
    fi
}

# Start AWX services
start_services() {
    log_info "Starting AWX services..."

    # Check if slurm network exists
    if ! docker network ls | grep -q "slurm-docker-cluster_default"; then
        log_warn "Slurm network not found. Starting Slurm cluster first..."
        log_warn "Run: cd .. && docker compose up -d"
        # Create the network anyway so AWX can start
        docker network create slurm-docker-cluster_default 2>/dev/null || true
    fi

    docker compose -f docker-compose.awx.yml up -d

    log_info "Waiting for AWX to be ready (this may take 2-3 minutes)..."
    local max_wait=180
    local waited=0
    while ! curl -sf http://localhost:${AWX_WEB_PORT:-8052}/api/v2/ping/ > /dev/null 2>&1; do
        if [[ $waited -ge $max_wait ]]; then
            log_error "AWX failed to start within $max_wait seconds"
            docker compose -f docker-compose.awx.yml logs awx-web
            exit 1
        fi
        echo -n "."
        sleep 5
        waited=$((waited + 5))
    done
    echo ""
    log_info "AWX is ready!"
}

# Configure AWX with initial resources
configure_awx() {
    log_info "Configuring AWX resources..."

    source .env
    local AWX_HOST="http://localhost:${AWX_WEB_PORT:-8052}"
    local AUTH="${AWX_ADMIN_USER}:${AWX_ADMIN_PASSWORD}"

    # Wait for API to be fully responsive
    sleep 5

    # Create Organization
    log_info "Creating organization..."
    curl -sf -X POST "$AWX_HOST/api/v2/organizations/" \
        -u "$AUTH" \
        -H "Content-Type: application/json" \
        -d '{"name": "Slurm HPC", "description": "Slurm cluster management"}' \
        > /dev/null 2>&1 || true

    # Get organization ID
    local ORG_ID=$(curl -sf "$AWX_HOST/api/v2/organizations/?name=Slurm+HPC" \
        -u "$AUTH" | python3 -c "import sys,json; print(json.load(sys.stdin)['results'][0]['id'])" 2>/dev/null || echo "1")

    # Create Machine Credential
    log_info "Creating machine credential..."
    curl -sf -X POST "$AWX_HOST/api/v2/credentials/" \
        -u "$AUTH" \
        -H "Content-Type: application/json" \
        -d "{
            \"name\": \"Slurm Nodes SSH\",
            \"description\": \"SSH credential for Slurm compute nodes\",
            \"organization\": $ORG_ID,
            \"credential_type\": 1,
            \"inputs\": {
                \"username\": \"root\",
                \"ssh_key_data\": \"\"
            }
        }" > /dev/null 2>&1 || true

    # Create Project (Manual - using local files)
    log_info "Creating project..."
    curl -sf -X POST "$AWX_HOST/api/v2/projects/" \
        -u "$AUTH" \
        -H "Content-Type: application/json" \
        -d "{
            \"name\": \"Slurm Maintenance\",
            \"description\": \"Rolling maintenance playbooks for Slurm\",
            \"organization\": $ORG_ID,
            \"scm_type\": \"manual\",
            \"local_path\": \"slurm-maintenance\"
        }" > /dev/null 2>&1 || true

    # Get project ID
    local PROJECT_ID=$(curl -sf "$AWX_HOST/api/v2/projects/?name=Slurm+Maintenance" \
        -u "$AUTH" | python3 -c "import sys,json; print(json.load(sys.stdin)['results'][0]['id'])" 2>/dev/null || echo "1")

    # Create Inventory
    log_info "Creating inventory..."
    curl -sf -X POST "$AWX_HOST/api/v2/inventories/" \
        -u "$AUTH" \
        -H "Content-Type: application/json" \
        -d "{
            \"name\": \"Slurm Cluster\",
            \"description\": \"Dynamic inventory from Slurm sinfo\",
            \"organization\": $ORG_ID
        }" > /dev/null 2>&1 || true

    # Get inventory ID
    local INV_ID=$(curl -sf "$AWX_HOST/api/v2/inventories/?name=Slurm+Cluster" \
        -u "$AUTH" | python3 -c "import sys,json; print(json.load(sys.stdin)['results'][0]['id'])" 2>/dev/null || echo "1")

    # Create Inventory Source (custom script)
    log_info "Creating inventory source..."
    curl -sf -X POST "$AWX_HOST/api/v2/inventory_sources/" \
        -u "$AUTH" \
        -H "Content-Type: application/json" \
        -d "{
            \"name\": \"Slurm Nodes\",
            \"description\": \"Dynamic inventory from sinfo\",
            \"inventory\": $INV_ID,
            \"source\": \"scm\",
            \"source_project\": $PROJECT_ID,
            \"source_path\": \"inventory/slurm_inventory.py\",
            \"update_on_launch\": true,
            \"overwrite\": true
        }" > /dev/null 2>&1 || true

    # Create Job Templates
    log_info "Creating job templates..."

    # Rolling Maintenance Template
    curl -sf -X POST "$AWX_HOST/api/v2/job_templates/" \
        -u "$AUTH" \
        -H "Content-Type: application/json" \
        -d "{
            \"name\": \"Rolling Maintenance\",
            \"description\": \"Execute rolling maintenance on Slurm nodes\",
            \"job_type\": \"run\",
            \"inventory\": $INV_ID,
            \"project\": $PROJECT_ID,
            \"playbook\": \"playbooks/rolling_maintenance.yml\",
            \"ask_variables_on_launch\": true,
            \"ask_limit_on_launch\": true,
            \"survey_enabled\": true
        }" > /dev/null 2>&1 || true

    # Emergency Stop Template
    curl -sf -X POST "$AWX_HOST/api/v2/job_templates/" \
        -u "$AUTH" \
        -H "Content-Type: application/json" \
        -d "{
            \"name\": \"EMERGENCY STOP\",
            \"description\": \"Halt all maintenance operations immediately\",
            \"job_type\": \"run\",
            \"inventory\": $INV_ID,
            \"project\": $PROJECT_ID,
            \"playbook\": \"playbooks/emergency_stop.yml\",
            \"extra_vars\": \"confirm: yes\",
            \"ask_variables_on_launch\": false
        }" > /dev/null 2>&1 || true

    # Emergency Resume Template
    curl -sf -X POST "$AWX_HOST/api/v2/job_templates/" \
        -u "$AUTH" \
        -H "Content-Type: application/json" \
        -d "{
            \"name\": \"Emergency Resume All\",
            \"description\": \"Resume all drained nodes immediately\",
            \"job_type\": \"run\",
            \"inventory\": $INV_ID,
            \"project\": $PROJECT_ID,
            \"playbook\": \"playbooks/emergency_resume.yml\",
            \"extra_vars\": \"confirm: yes\",
            \"ask_variables_on_launch\": false
        }" > /dev/null 2>&1 || true

    log_info "AWX configuration complete!"
}

# Add survey to Rolling Maintenance template
add_survey() {
    log_info "Adding survey to Rolling Maintenance template..."

    source .env
    local AWX_HOST="http://localhost:${AWX_WEB_PORT:-8052}"
    local AUTH="${AWX_ADMIN_USER}:${AWX_ADMIN_PASSWORD}"

    # Get template ID
    local TEMPLATE_ID=$(curl -sf "$AWX_HOST/api/v2/job_templates/?name=Rolling+Maintenance" \
        -u "$AUTH" | python3 -c "import sys,json; print(json.load(sys.stdin)['results'][0]['id'])" 2>/dev/null)

    if [[ -n "$TEMPLATE_ID" ]]; then
        curl -sf -X POST "$AWX_HOST/api/v2/job_templates/$TEMPLATE_ID/survey_spec/" \
            -u "$AUTH" \
            -H "Content-Type: application/json" \
            -d '{
                "name": "Maintenance Parameters",
                "description": "Configure rolling maintenance parameters",
                "spec": [
                    {
                        "question_name": "Target Nodes",
                        "question_description": "Which nodes to maintain (inventory group or pattern)",
                        "required": true,
                        "type": "text",
                        "variable": "target_nodes",
                        "default": "slurm_idle"
                    },
                    {
                        "question_name": "Batch Size",
                        "question_description": "Number of nodes to maintain concurrently",
                        "required": true,
                        "type": "integer",
                        "variable": "batch_size",
                        "min": 1,
                        "max": 50,
                        "default": 5
                    },
                    {
                        "question_name": "Maintenance Reason",
                        "question_description": "Reason for maintenance (visible in Slurm)",
                        "required": true,
                        "type": "text",
                        "variable": "maintenance_reason",
                        "default": "Scheduled maintenance"
                    },
                    {
                        "question_name": "Drain Timeout (seconds)",
                        "question_description": "Max time to wait for jobs to complete",
                        "required": true,
                        "type": "integer",
                        "variable": "drain_timeout",
                        "min": 60,
                        "max": 7200,
                        "default": 600
                    }
                ]
            }' > /dev/null 2>&1
        log_info "Survey added successfully"
    else
        log_warn "Could not find Rolling Maintenance template to add survey"
    fi
}

# Show status
show_status() {
    source .env 2>/dev/null || true
    echo ""
    echo "========================================"
    echo "AWX Status"
    echo "========================================"
    docker compose -f docker-compose.awx.yml ps
    echo ""
    echo "========================================"
    echo "Access Information"
    echo "========================================"
    echo "AWX Web UI:     http://localhost:${AWX_WEB_PORT:-8052}"
    echo "Pushgateway:    http://localhost:${PUSHGATEWAY_PORT:-9091}"
    echo ""
    if [[ -f .env ]]; then
        echo "Credentials:"
        grep -E "^AWX_ADMIN" .env
    fi
    echo "========================================"
}

# Main
case "${1:-}" in
    --start)
        setup_env
        start_services
        show_status
        ;;
    --config)
        configure_awx
        add_survey
        show_status
        ;;
    --status)
        show_status
        ;;
    --stop)
        docker compose -f docker-compose.awx.yml down
        ;;
    --clean)
        docker compose -f docker-compose.awx.yml down -v
        rm -f .env
        ;;
    *)
        setup_env
        setup_ssh
        setup_projects
        start_services
        configure_awx
        add_survey
        show_status
        ;;
esac
