#!/bin/bash
# scale.sh - Quick scaling script for Slurm playground
# Regenerates docker-compose and slurm.conf for N nodes

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

usage() {
    cat <<EOF
Usage: $0 <command> [options]

Commands:
    set <n>              Set cluster to n standard nodes (2-20)
    add <profile> <n>    Add n nodes of specified profile
    remove <node>        Remove a specific node
    status               Show current cluster topology
    reset                Reset to default 2-node cluster
    preset <name>        Apply a preset configuration
    list-presets         List available presets

Profiles: standard, highmem, highcpu, gpu

Examples:
    $0 set 10            # Scale to 10 standard nodes
    $0 add highmem 2     # Add 2 high-memory nodes
    $0 preset medium     # Apply medium preset
    $0 reset             # Reset to 2 nodes

EOF
    exit 1
}

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
    exit 1
}

# Check if playground CLI is installed
check_cli() {
    if command -v playground &> /dev/null; then
        return 0
    elif [ -f "$SCRIPT_DIR/cli/slurm_playground/main.py" ]; then
        return 1
    else
        return 2
    fi
}

# Generate slurm.conf from current state
generate_slurm_conf() {
    local num_standard=${1:-2}
    local num_highmem=${2:-0}
    local num_highcpu=${3:-0}
    local num_gpu=${4:-0}
    local config_dir="$PROJECT_DIR/config/25.05"
    local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    log_info "Generating slurm.conf for ${num_standard} standard, ${num_highmem} highmem, ${num_highcpu} highcpu, ${num_gpu} gpu nodes"

    # Build node definitions
    local node_defs=""
    local partition_nodes=""

    # Standard nodes
    if [ "$num_standard" -gt 0 ]; then
        if [ "$num_standard" -eq 1 ]; then
            node_defs+="NodeName=c1 CPUs=2 RealMemory=1000 State=UNKNOWN\n"
            partition_nodes="c1"
        else
            node_defs+="NodeName=c[1-${num_standard}] CPUs=2 RealMemory=1000 State=UNKNOWN\n"
            partition_nodes="c[1-${num_standard}]"
        fi
    fi

    # High-memory nodes
    local highmem_nodes=""
    if [ "$num_highmem" -gt 0 ]; then
        if [ "$num_highmem" -eq 1 ]; then
            node_defs+="NodeName=hm1 CPUs=2 RealMemory=4000 Features=highmem State=UNKNOWN\n"
            highmem_nodes="hm1"
        else
            node_defs+="NodeName=hm[1-${num_highmem}] CPUs=2 RealMemory=4000 Features=highmem State=UNKNOWN\n"
            highmem_nodes="hm[1-${num_highmem}]"
        fi
    fi

    # High-CPU nodes
    local highcpu_nodes=""
    if [ "$num_highcpu" -gt 0 ]; then
        if [ "$num_highcpu" -eq 1 ]; then
            node_defs+="NodeName=hc1 CPUs=4 RealMemory=2000 Features=highcpu State=UNKNOWN\n"
            highcpu_nodes="hc1"
        else
            node_defs+="NodeName=hc[1-${num_highcpu}] CPUs=4 RealMemory=2000 Features=highcpu State=UNKNOWN\n"
            highcpu_nodes="hc[1-${num_highcpu}]"
        fi
    fi

    # GPU nodes
    local gpu_nodes=""
    if [ "$num_gpu" -gt 0 ]; then
        if [ "$num_gpu" -eq 1 ]; then
            node_defs+="NodeName=gpu1 CPUs=2 RealMemory=2000 Features=gpu Gres=gpu:1 State=UNKNOWN\n"
            gpu_nodes="gpu1"
        else
            node_defs+="NodeName=gpu[1-${num_gpu}] CPUs=2 RealMemory=2000 Features=gpu Gres=gpu:1 State=UNKNOWN\n"
            gpu_nodes="gpu[1-${num_gpu}]"
        fi
    fi

    # Build partition definitions
    local partition_defs="PartitionName=normal Nodes=${partition_nodes} Default=YES MaxTime=INFINITE State=UP\n"

    if [ -n "$highmem_nodes" ]; then
        partition_defs+="PartitionName=highmem Nodes=${highmem_nodes} Default=NO MaxTime=24:00:00 State=UP\n"
    fi

    if [ -n "$highcpu_nodes" ]; then
        partition_defs+="PartitionName=highcpu Nodes=${highcpu_nodes} Default=NO MaxTime=12:00:00 State=UP\n"
    fi

    if [ -n "$gpu_nodes" ]; then
        partition_defs+="PartitionName=gpu Nodes=${gpu_nodes} Default=NO MaxTime=8:00:00 State=UP\n"
    fi

    # GRES configuration for GPU nodes
    local gres_types=""
    if [ "$num_gpu" -gt 0 ]; then
        gres_types="GresTypes=gpu"
    fi

    # Generate the config file
    cat > "$config_dir/slurm.conf" <<CONF
# slurm.conf - Slurm configuration file
# Generated by: playground/scale.sh
# Timestamp: ${timestamp}
#
# See slurm.conf(5) for more information.

#
# Cluster Identity
#
ClusterName=linux
SlurmctldHost=slurmctld

#
# Authentication
#
AuthType=auth/munge

#
# Paths
#
SlurmctldPidFile=/var/run/slurm/slurmctld.pid
SlurmctldPort=6817
SlurmdPidFile=/var/run/slurm/slurmd.pid
SlurmdPort=6818
SlurmdSpoolDir=/var/spool/slurm
SlurmUser=slurm
StateSaveLocation=/var/lib/slurm

#
# Process Tracking
#
ProctrackType=proctrack/linuxproc
TaskPlugin=task/affinity

#
# Timers
#
InactiveLimit=0
KillWait=30
MinJobAge=300
SlurmctldTimeout=120
SlurmdTimeout=300
Waittime=0

#
# Scheduling
#
SchedulerType=sched/backfill
SelectType=select/cons_tres

#
# Service Behavior
#
ReturnToService=1

#
# Accounting
#
AccountingStorageHost=slurmdbd
AccountingStorageType=accounting_storage/slurmdbd
JobCompLoc=/var/log/slurm/jobcomp.log
JobCompType=jobcomp/filetxt
JobAcctGatherType=jobacct_gather/linux
JobAcctGatherFrequency=30

#
# Logging
#
SlurmctldDebug=info
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdDebug=info
SlurmdLogFile=/var/log/slurm/slurmd.log

${gres_types}

#
# Compute Nodes
#
$(echo -e "$node_defs")
#
# Partitions
#
$(echo -e "$partition_defs")
CONF

    log_success "Generated slurm.conf at $config_dir/slurm.conf"
}

# Apply configuration to running cluster
apply_config() {
    log_info "Applying configuration to running cluster..."

    # Copy config to volume
    if docker compose -f "$PROJECT_DIR/docker-compose.yml" ps slurmctld --status running &>/dev/null; then
        docker compose -f "$PROJECT_DIR/docker-compose.yml" exec -T slurmctld scontrol reconfigure 2>/dev/null && \
            log_success "Configuration reloaded" || \
            log_warn "Could not reload configuration (cluster may not be running)"
    else
        log_warn "Cluster not running. Start with: make playground-start"
    fi
}

# Get current cluster status
get_status() {
    echo -e "${BLUE}=== Slurm Playground Status ===${NC}"
    echo ""

    if docker compose -f "$PROJECT_DIR/docker-compose.yml" ps slurmctld --status running &>/dev/null 2>&1; then
        echo -e "${GREEN}Cluster Status: RUNNING${NC}"
        echo ""

        echo "Node Information:"
        docker compose -f "$PROJECT_DIR/docker-compose.yml" exec -T slurmctld sinfo -N -l 2>/dev/null || echo "  (Could not retrieve node info)"
        echo ""

        echo "Partition Summary:"
        docker compose -f "$PROJECT_DIR/docker-compose.yml" exec -T slurmctld sinfo 2>/dev/null || echo "  (Could not retrieve partition info)"
        echo ""

        echo "Queue Status:"
        docker compose -f "$PROJECT_DIR/docker-compose.yml" exec -T slurmctld squeue 2>/dev/null || echo "  (Could not retrieve queue info)"
    else
        echo -e "${YELLOW}Cluster Status: NOT RUNNING${NC}"
        echo ""
        echo "Start the cluster with: make playground-start"
    fi
}

# Reset to default configuration
reset_cluster() {
    log_info "Resetting to default 2-node cluster..."
    generate_slurm_conf 2 0 0 0
    apply_config
    log_success "Cluster reset to default configuration"
}

# List available presets
list_presets() {
    echo -e "${BLUE}=== Available Presets ===${NC}"
    echo ""
    echo "minimal   - 2 standard nodes (basic testing)"
    echo "small     - 5 standard nodes"
    echo "medium    - 10 standard + 2 highmem + 2 highcpu"
    echo "large     - 20 standard + 2 highmem + 2 highcpu + 2 gpu"
    echo "gpu       - 4 standard + 4 gpu nodes"
    echo ""
    echo "Usage: $0 preset <name>"
}

# Apply a preset
apply_preset() {
    local preset=$1

    case $preset in
        minimal)
            generate_slurm_conf 2 0 0 0
            ;;
        small)
            generate_slurm_conf 5 0 0 0
            ;;
        medium)
            generate_slurm_conf 10 2 2 0
            ;;
        large)
            generate_slurm_conf 20 2 2 2
            ;;
        gpu|gpu_focused)
            generate_slurm_conf 4 0 0 4
            ;;
        *)
            log_error "Unknown preset: $preset. Use 'list-presets' to see available presets."
            ;;
    esac

    apply_config
}

# Main command handling
case "${1:-}" in
    set)
        [ -z "${2:-}" ] && log_error "Please specify number of nodes"
        num=$2
        [ "$num" -lt 1 ] || [ "$num" -gt 20 ] && log_error "Number of nodes must be between 1 and 20"
        generate_slurm_conf "$num" 0 0 0
        apply_config
        ;;
    add)
        [ -z "${2:-}" ] && log_error "Please specify profile (standard, highmem, highcpu, gpu)"
        [ -z "${3:-}" ] && log_error "Please specify number of nodes to add"
        log_warn "Dynamic add not yet implemented. Use 'preset' command instead."
        ;;
    remove)
        [ -z "${2:-}" ] && log_error "Please specify node to remove"
        log_warn "Dynamic remove not yet implemented. Use 'preset' or 'set' command instead."
        ;;
    status)
        get_status
        ;;
    reset)
        reset_cluster
        ;;
    preset)
        [ -z "${2:-}" ] && log_error "Please specify preset name. Use 'list-presets' to see options."
        apply_preset "$2"
        ;;
    list-presets)
        list_presets
        ;;
    *)
        usage
        ;;
esac
